source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MaterialCard_Example', :exclusive => true do
  pod 'MaterialCard', :path => '../'
end

target 'MaterialCard_Tests', :exclusive => true do
  pod 'MaterialCard', :path => '../'

  
end
